version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bd-clientes-pedidos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm start
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/bd-clientes-pedidos

volumes:
  postgres_data:
